/*
    Email transporter (mailer)

    Responsibilities:
    - Create and export a Nodemailer transporter configured from environment
      variables.
    - When SMTP credentials are absent (local development), automatically
      create a temporary Ethereal test account. Ethereal catches all outgoing
      emails and provides a preview URL — no real emails are ever delivered,
      and no sign-up is required.

    How it works:
    - On first call to `getTransporter()` the module checks whether SMTP_HOST
      is set in the environment.
        • If yes  → create a real SMTP transporter.
        • If no   → call Ethereal's `createTestAccount()`, which returns a
                    temporary username + password, then create an SMTP transport
                    pointing at Ethereal's servers.
    - The transporter is cached in a module-level variable so the Ethereal
      account is only created once per process start.
    - `sendMail(options)` wraps the underlying transporter. In development it
      also logs the Nodemailer preview URL so you can open the email in your
      browser without setting up a mail client.

    Usage:
        import { sendMail } from './mailer.js';
        const info = await sendMail({ to, subject, html, text });
*/

import nodemailer from 'nodemailer';
import { config } from '../config.js';

// Module-level transporter promise cache. Initialised lazily on first send.
let _transporterPromise = null;

/**
 * Returns a ready Nodemailer transporter. Creates it on first call.
 *
 * The async initialisation (Ethereal account creation) is handled here so
 * callers don't need to worry about setup — they just call `sendMail`.
 *
 * @returns {Promise<nodemailer.Transporter>}
 */
async function getTransporter() {
    if (_transporterPromise) return _transporterPromise;

    _transporterPromise = (async () => {
        if (config.SMTP_HOST) {
            // ── Production / staging path ─────────────────────────────────────────
            // A real SMTP host is configured. Create a transporter using those
            // credentials. SMTP_PORT defaults to 587 (STARTTLS / submission).
            console.log(`[mailer] Using real SMTP server: ${config.SMTP_HOST}:${config.SMTP_PORT}`);
            return nodemailer.createTransport({
                host: config.SMTP_HOST,
                port: config.SMTP_PORT,
                secure: config.SMTP_PORT === 465,
                auth: {
                    user: config.SMTP_USER,
                    pass: config.SMTP_PASS
                }
            });
        } else {
            // ── Development path (Ethereal) ───────────────────────────────────────
            // No real SMTP credentials → create a free Ethereal test account.
            console.log('[mailer] No SMTP_HOST set — creating Ethereal test account for development...');
            const testAccount = await nodemailer.createTestAccount();
            console.log(`[mailer] Ethereal account ready: ${testAccount.user}`);

            return nodemailer.createTransport({
                host: 'smtp.ethereal.email',
                port: 587,
                secure: false,          // STARTTLS on port 587
                auth: {
                    user: testAccount.user,
                    pass: testAccount.pass
                }
            });
        }
    })();

    return _transporterPromise;
}

/**
 * Send an email.
 *
 * @param {object} options
 * @param {string}   options.to       - Recipient address (e.g. "alice@example.com")
 * @param {string}   options.subject  - Email subject line
 * @param {string}   options.html     - HTML body (rich email content)
 * @param {string}   [options.text]   - Plain-text fallback for clients that
 *                                      don't render HTML
 *
 * @returns {Promise<nodemailer.SentMessageInfo>} - Nodemailer result object.
 *   In development, use `nodemailer.getTestMessageUrl(result)` on the returned
 *   value to get the Ethereal preview link.
 */
export async function sendMail({ to, subject, html, text }) {
    // Synthetic bot addresses (e.g. bot-0@stockey.local) generated by high-frequency
    // market-making bots skip external network SMTP calls to prevent hitting
    // public Ethereal rate limits (429 Rate limited).
    if (typeof to === 'string' && (to.endsWith('.local') || to.endsWith('.test') || to.startsWith('bot-'))) {
        return {
            messageId: `<bot-simulated-${Date.now()}-${Math.random().toString(36).slice(2)}@stockey.local>`,
            accepted: [to],
            rejected: [],
            pending: [],
            response: '250 2.0.0 OK (synthetic bot email simulated)'
        };
    }

    const transporter = await getTransporter();

    const result = await transporter.sendMail({
        from: config.SMTP_FROM,   // "Stockey <noreply@stockey.dev>"
        to,
        subject,
        html,
        text: text ?? ''          // Nodemailer accepts empty string
    });

    // In development, Nodemailer provides a URL to preview the captured email
    // on the Ethereal web interface. Log it so you can click it directly in
    // the terminal.
    const previewUrl = nodemailer.getTestMessageUrl(result);
    if (previewUrl) {
        console.log(`[mailer] 📧 Preview email at: ${previewUrl}`);
    }

    return result;
}
