/*
    Notifications queue

    Responsibilities:
    - Define the BullMQ `notifications` queue that carries all outgoing email
      jobs.
    - Export typed enqueue helpers so the rest of the codebase never
      hardcodes job names or shapes — they call a named function instead.

    Job names (used to route jobs inside the worker):
    ┌─────────────────────────┬──────────────────────────────────────────────┐
    │ Job name                │ Triggered by                                 │
    ├─────────────────────────┼──────────────────────────────────────────────┤
    │ trade-confirmation      │ Matching engine after every trade            │
    │ otp-email               │ OTP controller when user requests an OTP     │
    │ daily-pnl-summary       │ Scheduler after market close                 │
    └─────────────────────────┴──────────────────────────────────────────────┘

    BullMQ pattern notes:
    - This file only creates the Queue (the producer side).
    - The corresponding Worker (consumer) lives in notifications.worker.js.
    - Both use the same Redis connection string but different ioredis clients.
      BullMQ requires `maxRetriesPerRequest: null` on ioredis connections to
      prevent internal request timeouts from crashing the queue.
    - `removeOnComplete` and `removeOnFail` keep Redis storage bounded:
        • completed jobs are pruned after 500 entries
        • failed jobs are kept longer (2000) for post-mortem inspection
    - Email jobs run at a lower priority than matching jobs. BullMQ uses
      integer priorities where 1 is the highest. We use priority 5 for emails.
*/

import { createRequire } from 'node:module';
import { Redis } from 'ioredis';
import { config } from '../config.js';

// BullMQ ships as an ESM package but has interop issues with the current
// Node.js + ESM toolchain for dynamic class inheritance. Loading the CJS
// build via `createRequire` is the established workaround used elsewhere
// in this project.
const require = createRequire(import.meta.url);
const { Queue: QueueCjs } = require('bullmq/dist/cjs/index.js');

// Each queue needs its own ioredis client. BullMQ manages the lifecycle
// of this connection internally; we just configure it.
const connection = new Redis(config.REDIS_URL, {
    maxRetriesPerRequest: null   // required by BullMQ to prevent internal timeouts
});
connection.on('error', (err) => console.error('[notifications-queue] Redis error', err));

// ─────────────────────────────────────────────────────────────────────────────
// Queue definition
// ─────────────────────────────────────────────────────────────────────────────

export const notificationsQueue = new QueueCjs('notifications', {
    connection,
    defaultJobOptions: {
        // Retry up to 5 times with exponential backoff starting at 1 s.
        // This handles transient SMTP errors (rate limits, timeouts) gracefully.
        attempts: 5,
        backoff: { type: 'exponential', delay: 1_000 },

        // Email jobs are lower priority than order-matching (priority 1).
        // Lower number = higher priority in BullMQ.
        priority: 5,

        // Keep a rolling window of the last 500 successful jobs for debugging.
        // Keep the last 2000 failed jobs so you can inspect failures.
        removeOnComplete: 500,
        removeOnFail: 2_000
    }
});

// ─────────────────────────────────────────────────────────────────────────────
// Enqueue helpers
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Enqueue a trade confirmation email for a single user (buyer or seller).
 *
 * Called twice per trade execution — once for the buyer's order and once for
 * the seller's order. Each call carries only the data relevant to that user's
 * perspective (their side, their order ID, etc.).
 *
 * @param {object} payload
 * @param {string}  payload.userId       - Recipient's user ID (for notification log)
 * @param {string}  payload.email        - Recipient's email address
 * @param {string}  payload.side         - 'buy' or 'sell'
 * @param {string}  payload.stockSymbol
 * @param {number}  payload.quantity
 * @param {number}  payload.price        - Execution price
 * @param {number}  payload.total        - quantity × price
 * @param {string}  payload.orderId      - The user's order UUID
 * @param {string}  payload.executedAt   - ISO timestamp
 */
export async function enqueueTradeConfirmation(payload) {
    // Use a composite job ID to prevent duplicate emails if the matching engine
    // retries. Format: "trade-confirm:{orderId}" is unique per order.
    return notificationsQueue.add(
        'trade-confirmation',
        payload,
        { jobId: `trade-confirm:${payload.orderId}` }
    );
}

/**
 * Enqueue an OTP email.
 *
 * The OTP itself is generated by the controller and stored in Redis before
 * this job is enqueued. The worker just sends the email — it does not generate
 * or validate the OTP.
 *
 * @param {object} payload
 * @param {string}  payload.userId    - For the notification log
 * @param {string}  payload.email     - Recipient email
 * @param {string}  payload.otp       - The 6-digit code (already stored in Redis)
 * @param {string}  payload.action    - Human-readable action e.g. "withdraw funds"
 */
export async function enqueueOtpEmail(payload) {
    // OTP jobs are time-sensitive (10-minute expiry), so we give them a
    // slightly higher priority (3) than regular notifications (5).
    return notificationsQueue.add(
        'otp-email',
        payload,
        {
            priority: 3,
            // No jobId deduplication: users can request multiple OTPs and each
            // one should produce a new email.
        }
    );
}

/**
 * Enqueue a daily P&L summary email for a single user.
 *
 * Called by the scheduler worker after market close — one job per user who
 * has any portfolio activity.
 *
 * @param {object} payload
 * @param {string}  payload.userId      - For the notification log
 * @param {string}  payload.email       - Recipient email
 * @param {string}  payload.date        - ISO string of the market close date
 */
export async function enqueueDailyPnlEmail(payload) {
    // Use a date-scoped job ID to avoid sending duplicate summaries if the
    // scheduler fires more than once (e.g. due to a crash + restart).
    const dateKey = new Date(payload.date).toISOString().slice(0, 10); // YYYY-MM-DD
    return notificationsQueue.add(
        'daily-pnl-summary',
        payload,
        {
            priority: 8,  // lowest priority — bulk operation
            jobId: `daily-pnl:${payload.userId}:${dateKey}`
        }
    );
}

/**
 * Close the queue and its Redis connection cleanly.
 * Called during graceful shutdown.
 */
export async function closeNotificationsQueue() {
    await notificationsQueue.close();
    await connection.quit();
}
